{{- if .Values.config }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "crm-web.fullname" . }}-config
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "crm-web.labels" . | nindent 4 }}
data:
  {{- toYaml .Values.config | nindent 2 }}
{{- end }}
